{{- $release := .Release -}}
{{- $chart := .Chart -}}
{{- $values := .Values -}}
{{- $chartVersion := printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}

{{ range $key, $function := .Values.functions }}
{{- $fullname := printf "%s-%s-%s" $release.Name $chart.Name $function.name | trunc 63 | trimSuffix "-" -}}
{{- $name := printf "%s-%s" $chart.Name $function.name | trunc 63 -}}

---
# function {{ $function.name }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ $name }}
    chart: {{ $chartVersion }}
    release: {{ $release.Name }}
    heritage: {{ $release.Service }}
    function: {{ $function.name }}
spec:
  replicas: {{ default $values.defaults.replicas $function.replicas }}
  selector:
    matchLabels:
      app: {{ $name }}
      release: {{ $release.Name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        release: {{ $release.Name }}
    spec:
      containers:
        - name: {{ $chart.Name }}
          command: {{ default $values.defaults.command $function.command | toJson }}
          image: "{{ $values.image.repository }}:{{ $values.image.tag }}"
          imagePullPolicy: {{ $values.image.pullPolicy }}
          ports:
            - name: healthz
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
          readinessProbe:
            httpGet:
              path: /healthz
              port: healthz
          env:
            - name: TOPIC
              value: {{ default $function.name $function.topic }}
            - name: CHANNEL
              value: {{ default "default" $function.channel }}
{{ default $values.defaults.env $function.env | toYaml | indent 12 }}
{{- with default $values.defaults.resources $function.resources }}
          resources:
{{ . | toYaml | indent 12 }}
{{- end }}
{{- with default $values.defaults.nodeSelector $function.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with default $values.defaults.affinity $function.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with default $values.defaults.tolerations $function.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{ end -}}
