[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  name = "github.com/nsqio/go-nsq"
  version = "1.0.7"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
