---
# Source: gateway/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kubefuncs
  name: kubefuncs-gateway
  labels:
    app: gateway
    chart: gateway-v0.0.1
    release: kubefuncs
    heritage: Tiller
data:
  routes.json: "{\"/test/\":\"test\"}"

---
# Source: gateway/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: kubefuncs
  name: kubefuncs-gateway
  labels:
    app: gateway
    chart: gateway-v0.0.1
    release: kubefuncs
    heritage: Tiller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
      annotations:
        kubefuncs.io/checksum-config: f2599870b4416a1beb72703d2043f5d073a86b18be82edd5c61c231950b49f7e
    spec:
      containers:
      - name: gateway
        image: localhost:5000/gateway:v0.0.1
        resources:
          {}
          
        command:
        - /bin/gateway
        - --config=/etc/gateway/routes.json
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: NSQ_NSQD_PORT
          value: "4150"
          
        - name: NSQ_NSQD_ADDR
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
          
        - name: NSQ_LOOKUPD_ADDR
          value: kubefuncs-nsq-lookupd.kubefuncs.svc.cluster.local
          
        - name: NSQ_LOOKUPD_PORT
          value: "4161"
          
        volumeMounts:
        - name: config-volume
          mountPath: /etc/gateway
      volumes:
        - name: config-volume
          configMap:
            name: kubefuncs-gateway

---
# Source: gateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: kubefuncs
  name: kubefuncs-gateway
  labels:
    app: gateway
    chart: gateway-v0.0.1
    release: kubefuncs
    heritage: Tiller
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
    targetPort: 8080
  selector:
    app: gateway

