# Image specification. These values must be set by the user.
image:
  repository: null
  tag: null
  pullPolicy: IfNotPresent

# Default configuration, these will be applied to functions as a default value.
defaults:
  replicas: 1
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  command: null
  env:
    - name: NSQ_NSQD_PORT
      value: '4150'
    - name: NSQ_NSQD_ADDR
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: NSQ_LOOKUPD_ADDR
      value: kubefuncs-nsq-lookupd.kubefuncs.svc.cluster.local
    - name: NSQ_LOOKUPD_PORT
      value: '4161'

# The functions block defines a list of function objects. A function object
# includes the following fields:
# - name: The name of the function and default topic name.
# - channel: The nsq channel of the function.
# - command: Kubernetes command.
# - replicas: Replica count for the initial pool.
# - resources: Kubernetes resources block.
# - nodeSelector: Kubernetes nodeSelector block.
# - tolerations: Kubernetes tolerations block.
# - affinity: Kubernetes affinity block.
# - command: Kubernetes command block.
# - env: Kubernetes env block.
functions: []
# - name: archiver
#   topic: test
#   channel: responder
#   command:
#     - /bin/app
#     - -handler=archiver
