apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "admin.fullname" . }}
  labels:
    app: {{ template "admin.name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 4161
    protocol: TCP
    name: http
    targetPort: 4171
  selector:
    app: {{ template "admin.name" . }}
