{{- define "chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{ range _, $function := .Values.functions }}
{{- with fullname := printf "%s-%s-%s" .Release.Name .Chart.Name $function.name | trunc 63 | trimSuffix "-" -}}
{{- with name := printf "%s-%s" .Chart.Name $function.name | trunc 63 -}}
---
# function {{ $function.name }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ $name }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    function: {{ $function.name }}
spec:
  replicas: {{ default .Values.defaults.replicas $function.replicas }}
  selector:
    matchLabels:
      app: {{ $name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          command: {{ default .Values.defaults.command $function.command }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: healthz
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
          readinessProbe:
            httpGet:
              path: /healthz
              port: healthz
          env:
            - name: TOPIC
              value: {{ $function.name }}
{{ default .Values.defaults.env $function.env | toYaml | indent 12 }}
          resources:
{{ default .Values.defaults.resources $function.resources | toYaml | indent 12 }}
    {{- with default .Values.defaults.nodeSelector $function.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with default .Values.defaults.affinity $function.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with default .Values.defaults.tolerations $function.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{ end }}
{{ end }}
{{ end }}
