apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "admin.fullname" . }}
  labels:
    app: {{ template "admin.name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "admin.name" . }}
    spec:
      containers:
      - name: {{ template "admin.name" . }}
        image: nsqio/nsq:{{ .Chart.AppVersion }}
        resources:
{{ toYaml .Values.admin.resources | indent 10 }}
        command:
        - /nsqadmin
        - --lookupd-http-address={{ template "dns.lookupd" . }}:4161
        ports:
        - name: http
          containerPort: 4171
