apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "fullname" . }}-lookupd
  labels:
    app: {{ template "name" . }}-lookupd
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 4160
    protocol: TCP
    name: tcp
    targetPort: 4160
  - port: 4161
    protocol: TCP
    name: http
    targetPort: 4161
  selector:
    app: {{ template "name" . }}-lookupd
