apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "lookupd.fullname" . }}
  labels:
    app: {{ template "lookupd.name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.lookupd.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "lookupd.name" . }}
    spec:
      containers:
      - name: {{ template "lookupd.name" . }}
        image: nsqio/nsq:{{ .Chart.Version }}
        resources:
{{ toYaml .Values.lookupd.resources | indent 10 }}
        command:
        - /nsqlookupd
        ports:
        - name: tcp
          containerPort: 4160
        - name: http
          containerPort: 4161
