apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "nsqd.fullname" . }}
  labels:
    app: {{ template "nsqd.name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "nsqd.name" . }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9117'
    spec:
      containers:
      - name: nsqd
        image: nsqio/nsq:{{ .Chart.APPVersion }}
        resources:
{{ toYaml .Values.nsqd.resources | indent 10 }}
        command:
        - /nsqd
        - --lookupd-tcp-address={{ template "dns.lookupd" . }}:4160
        - --broadcast-address=$(NODE_IP)
        ports:
        - name: tcp
          containerPort: 4150
          hostPort: 4150
        - name: http
          containerPort: 4151
          hostPort: 4151
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      - name: exporter
        image: lovoo/nsq_exporter:latest
        command:
        - /nsq_exporter
        - -nsqd.addr=http://$(NODE_IP):4151
        ports:
        - name: http
          containerPort: 9117
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
