image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

defaults:
  replicas: 1
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  command: null
  env:
    - name: NSQ_NSQD_PORT
      value: '4150'
    - name: NSQ_NSQD_ADDR
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: NSQ_LOOKUPD_ADDR
      value: kubefuncs-nsq-lookupd.kubefuncs.svc.cluster.local
    - name: NSQ_LOOKUPD_PORT
      value: '4161'

functions: []
